# Generated by https://quicktype.io

from enum import Enum
from typing import List


class Difficulty(Enum):
    EASY = "easy"
    HARD = "hard"
    MEDIUM = "medium"


class TypeEnum(Enum):
    BOOLEAN = "boolean"
    MULTIPLE = "multiple"


class Result:
    category: str
    type: TypeEnum
    difficulty: Difficulty
    question: str
    correct_answer: str
    incorrect_answers: List[str]

    def __init__(self, category: str, type: TypeEnum, difficulty: Difficulty, question: str, correct_answer: str, incorrect_answers: List[str]) -> None:
        self.category = category
        self.type = type
        self.difficulty = difficulty
        self.question = question
        self.correct_answer = correct_answer
        self.incorrect_answers = incorrect_answers


class Question:
    response_code: int
    results: List[Result]

    def __init__(self, response_code: int, results: List[Result]) -> None:
        self.response_code = response_code
        self.results = results
